### ISSUE TITLE
site.baseurl problems

### ISSUE THREAD

**Issue by lokenx** [barryclark/jekyll-now#160]
I'm having issues with the {{ site.baseurl }} tag. It's for my main user page with a custom domain so I set the config variable to nothing, just the default `""` and updated my CNAME file and website serves fine. However on a post page, the title link ( `href="{{ site.baseurl }}"`) doesn't work it comes up as empty when viewing the source code.  However, links using ` href="{{ site.baseurl }}{{ post.url }}"` get done correct as `/page-name/` and work fine.

Am I missing something somewhere?

**Comment by barryclark** [comment]
Thanks for the issue, @lokenx.

I notice you got up and running at http://8bits.ca/ - which looks lovely! Nice job :grinning: 

I couldn't find `href="{{ site.baseurl }}"` in the Jekyll Now codebase. Whenever I use that, I give it a trailing slash (`href="{{ site.baseurl }}/"`), so that it'd go to the homepage. Maybe that was the problem?

**Comment by lokenx** [comment]
Ah OK, that makes sense. I temporarily switched to a base jekyll with someone elses theme but I'd rather switch back to yours.

**Comment by barryclark** [comment]
Gottit. Glad it's working correctly now :)
