### ISSUE TITLE
Sass compile error

### ISSUE THREAD

**Issue by jimmieego** [barryclark/jekyll-now#237]
I was trying to use Sass to compile the style.scss file. I inputted the following at the command line:

<code>sass style.scss style.css</code>

And the error I get is:

Error: Invalid CSS after "@import "reset"": expected "{", was ";"
        on line 8 of style.scss
  Use --trace for backtrace.

Could you look into this? Thanks!

My Sass version is 3.4.16

**Comment by barryclark** [comment]
Are you still running into this problem, @jimmieego?

**Comment by jimmieego** [comment]
Yes. I still see the error as I described above.

**Comment by barryclark** [comment]
Oh, this is because you're trying to compile the style.scss file directly. That's not going to work as the first two lines of triple dashes at the top of the .scss file will mess it up (Jekyll needs these - http://jekyllrb.com/docs/assets/). Let Jekyll compile it for you when you run `jekyll build --watch`, you don't need to `sass style.scss style.css`.

**Comment by jimmieego** [comment]
I see. Thanks for the helpful clarification!
