### ISSUE TITLE
Blog in User sub-repository

### ISSUE THREAD

**Issue by av-maslov** [barryclark/jekyll-now#69]
Hello,

> If you're hosting your site at a Project repository on GitHub pages 
> (http://yourusername.github.io/repository-name)
> and **NOT your User repository** (http://yourusername.github.io)
> then add in the baseurl here, like this: "/repository-name"

Do you plan to enable this feature ( to host blog in User sub repository ) in the feature?
It would be very convenient for those users who host their personal web pages on GitHub.

Thank you

**Comment by KenNewcomb** [comment]
Hi @barryclark !

I have this issue as well. I would be willing to work with you to get to the bottom of it.

Thanks!

Ken Newcomb

**Comment by barryclark** [comment]
@KenNewcomb @av-maslov thanks for the info on this. 

Are you guys still seeing this problem? I tried, but can't reproduce it. I don't get any style.scss errors after forking, or when building locally. It looks like that might have been a problem a couple of weeks ago that GitHub have since fixed.

Shoot me links to your repo + sites if you're still having a problem and I'll take a look?

Cheers,
Barry

**Comment by barryclark** [comment]
From http://kennewcomb.github.io it looks like you're up and running now, @KenNewcomb?

**Comment by av-maslov** [comment]
Hi Barry,

I just moved the blog into separate account

**Comment by KenNewcomb** [comment]
@barryclark Yep! I wasn't able to build with jekyll-now, but I forked Poole's Hyde theme and my setup now works. I'm not totally sure what the problem was.
