### ISSUE TITLE
Add feedburner support

### ISSUE THREAD

**Issue by markphelps** [barryclark/jekyll-now#70]
Perhaps something like what was done in Jekyll Bootstrap https://github.com/astropanic/jekyll-bootstrap/commit/3f88703fc02782ca0345f53f312660ec4843a3ea

**Comment by barryclark** [comment]
Thanks for the suggestion, @markphelps! Much appreciated. 

With Jekyll Now the goal is really to give people the most lightweight solution possible out of the box to be able to start a simple blog, so that folk can then add additional bits as they need them. I cut a LOT of extra features and things that I use out (even things like RSS) as I don't want to add any weight that won't be used by the majority of people.

This sounds like a great thing for individuals to add that need it. Going to pass on adding it into Jekyll Now for now, and can reconsider if many additional people request it.

Thanks again! :)
